// Code generated by protoc-gen-ecode v0.1, DO NOT EDIT.
// source: leafgo_error.proto

/*
Package leaf_go is a generated ecode package.
This code was generated with kratos/tool/protobuf/protoc-gen-ecode v0.1.

package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

It is generated from these files:
	leafgo_error.proto
*/
package leaf_go

import (
	"github.com/bilibili/kratos/pkg/ecode"
)

// to suppressed 'imported but not used warning'
var _ ecode.Codes

// LeafGoErrCode ecode
var (
	LAST_TIME_GT_CURRENT_TIME = ecode.New(256)
)
