// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/jerryzhou343/leaf-go/api/rpc"
	"github.com/jerryzhou343/leaf-go/app/executor/cmd"
	"github.com/jerryzhou343/leaf-go/app/executor/query"
	"github.com/jerryzhou343/leaf-go/domain/aggregate/snowflake"
	"github.com/jerryzhou343/leaf-go/infra/conf"
	"github.com/jerryzhou343/leaf-go/infra/repo/demo"
	"github.com/jerryzhou343/leaf-go/infra/server/grpc"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	config, err := conf.NewConf()
	if err != nil {
		return nil, nil, err
	}
	snowflakeSnowflake, err := snowflake.NewSnowflake(config)
	if err != nil {
		return nil, nil, err
	}
	appCmd, err := cmd.NewAppCmd(config, snowflakeSnowflake)
	if err != nil {
		return nil, nil, err
	}
	repo, err := demo.NewRepo(config)
	if err != nil {
		return nil, nil, err
	}
	appQuery := query.NewAppQuery(repo)
	handler := rpc.NewHandler(appCmd, appQuery)
	server, err := grpc.New(handler, config)
	if err != nil {
		return nil, nil, err
	}
	app, cleanup, err := NewApp(handler, server, config)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}
